version: "3"
services:
  external-processor-api:
    image: adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine
    volumes:
      - './:/payment-processing-gateway'
    working_dir: '/payment-processing-gateway'
    command: sh -c "./gradlew external-processor-api:startMock"
    ports:
      - "8500:8500"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'payments'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - my-db:/var/lib/mysql
  payments:
    image: unzer-interviewing/payments-service
    container_name: payments-service
    build:
      context: payments-service
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
volumes:
  my-db:
